#!/bin/sh
clear
pip install -r requirements.txt
pip install --upgrade passlib[bcrypt]
pip install "psycopg[binary]"
uv sync
# pip install "fastapi[standard]"
# python -m pip install sqlalchemy[asyncio]
# python -m pip install sqlmodel[asyncio]
# 📌 What each one does:
# sqlalchemy → DB layer
# passlib[bcrypt] → password hashing
# python-jose → JWT
# python-multipart → OAuth2 form parsing
# fastapi → API
# uvicorn → server

