#!/bin/sh
#reset
# echo "Running alembic upgrade head"
# alembic upgrade head
# echo "Running Base.metadata.create_all(bind=engine)"
# python Base.metadata.create_all(bind=engine)
echo "python -m app.dev_seed"
python -m app.dev_seed_users

