#!/bin/sh
reset
# Setup the backend
#pip install -r requirements.txt
# Run the backend
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
#uvicorn app.main:app --reload
#uvicorn app.main:app --host 0.0.0.0 --port 8000

